version: "3.8"
services:
  backend:
    build: ./back-end
    ports:
      - "3000:3000"
    env_file:
      - ./back-end/.env

  frontend:
    build: ./front-end
    ports:
      - "8081:8081"
    env_file:
      - ./front-end/.env
