import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import workoutStyles from "@/styles/HomePage.module.css";

import Header from "@/components/header";
import postStyle from "../styles/Posts.module.css";
import { useState, useEffect } from "react";
import Link from "next/link";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { GetServerSidePropsContext } from "next/types";
import router from "next/router";
import { Workout } from "@/types";
import WorkoutService from "@/services/WorkoutService";
import useInterval from "use-interval";
import { mutate } from "swr";
import TodaysWorkouts from "@/components/workouts/todaysWorkouts";
import WeekWorkouts from "@/components/workouts/WeekWorkouts";

//test

const Home: React.FC = () => {
  const [isLoggedIn, setIsLoggedIn] = useState<boolean | null>(null);
  const [workouts, setWorkouts] = useState<Array<Workout>>([]);
  const [token, setToken] = useState<string | null>(null);

  const fetchWorkouts = async () => {
    try {
      const response = await WorkoutService.getAllWorkouts();
      const data = await response.json();
      const parsedData = data.map((workout: Workout) => ({
        ...workout,
        date: new Date(workout.date),
      }));
      setWorkouts(parsedData);
    } catch (error) {
      console.error("Failed to fetch workouts:", error);
    }
  };

  useInterval(() => {
    if (token) {
      mutate(["workouts", token]);
    }
  }, 2000);

  useEffect(() => {
    const userData = sessionStorage.getItem("loggedInUser");
    if (userData) {
      try {
        const parsedData = JSON.parse(userData);
        const { email, token } = parsedData;
        setToken(token);
        setIsLoggedIn(!!token);
      } catch (error) {
        console.error("Error parsing session storage data:", error);
        setIsLoggedIn(false);
      }
    } else {
      setIsLoggedIn(false);
    }

    fetchWorkouts();
  }, []);

  return (
    <>
      <Head>
        <title> Home </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.homePage}>
        <Header />
        <main className={styles.mainHome}>
          <section className={styles.title}>
            <Image
              src="/pictures/logo.png" // pad binnen public
              alt="Fitness-Cloud logo"
              width={200} // pas aan wat je mooi vindt
              height={130} // idem
              priority // preload: sneller zichtbaar
            />
          </section>

          <section
            className={`${workoutStyles.todaysWorkoutsPage} ${workoutStyles.sectionGap}`}
          >
            <TodaysWorkouts workouts={workouts}></TodaysWorkouts>
          </section>
          <section
            className={`${workoutStyles.weekWorkoutsPage} ${workoutStyles.sectionGap}`}
          >
            <WeekWorkouts workouts={workouts} />
          </section>
        </main>
      </div>
    </>
  );
};

export default Home;
