name: Deploy Functions and Frontend

on:
  push:
    branches:
      - main

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: "functionCloudNativeGroup25"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "../azure-functions/dist"
  NODE_VERSION: "20.x"

jobs:
  upload-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Upload Script
        run: |
          chmod +x ./upload-site.sh
          ./upload-site.sh
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}

  build-and-deploy-functions:
    runs-on: windows-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Install and Build Azure Functions"
        shell: pwsh
        run: |
          pushd './azure-functions'
          npm install
          npm run build
          popd

      - name: "Copy compiled function folders to dist root"
        shell: pwsh
        run: |
          $srcRoot = "./azure-functions/src"
          $compiledRoot = "./azure-functions/dist/src"
          $distRoot = "./azure-functions/dist"

          Get-ChildItem -Path $srcRoot -Directory | ForEach-Object {
            $funcName = $_.Name
            $srcFuncDir = $_.FullName
            $compiledFuncDir = Join-Path $compiledRoot $funcName
            $destFuncDir = Join-Path $distRoot $funcName

            if (-not (Test-Path $destFuncDir)) {
              New-Item -ItemType Directory -Path $destFuncDir | Out-Null
            }

            # Copy function.json from src
            Copy-Item -Path "$srcFuncDir/function.json" -Destination $destFuncDir -Force

            # Copy compiled JS files from dist/src
            Copy-Item -Path "$compiledFuncDir/*" -Destination $destFuncDir -Recurse -Force
          }

      - name: "Copy host.json to dist"
        shell: pwsh
        run: |
          Copy-Item -Path "./azure-functions/host.json" -Destination "./azure-functions/dist" -Force

      - name: "Debug: List dist folder contents"
        shell: pwsh
        run: |
          Get-ChildItem -Path "./azure-functions/dist" -Recurse

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        with:
          app-name: "functionCloudNativeGroup25"
          package: "./azure-functions/dist"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FUNCTIONAPP }}
