name: Build and deploy Node.js backend & frontend to Azure Web Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build, and test (backend)
        run: |
          npm install
          npm run build --if-present

      - name: Zip backend artifact
        run: zip -r backend.zip ./

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: ./back-end/backend.zip

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-end
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build, and test (frontend)
        run: |
          npm install
          npm run build --if-present

      - name: Zip frontend artifact
        run: zip -r frontend.zip ./

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: ./front-end/frontend.zip

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact

      - name: Unzip backend artifact
        run: unzip backend.zip

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "cloud-native-backEnd"
          slot-name: "Production"
          package: .

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact

      - name: Unzip frontend artifact
        run: unzip frontend.zip

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Cloud-Native-Engineering"
          slot-name: "Production"
          package: .
